### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by KevinNovak** [timotejroiko/discord.js-light#10]
When using TypeScript, the editor is unable to find the type declarations file (I'm guessing since it is included in discord.js but not in discord.js-light?):

![Missing TypeScript](https://i.imgur.com/qQccmja.png)

Is there a way to include or redirect typescript definitions to make discord.js-light usable with typescript?

**Comment by timotejroiko** [comment]
i'll look into it

**Comment by timotejroiko** [comment]
i've added some basic typings in 8763310, feel free to test them out. (i hope they work, im not a ts dev)
I'll try to add the rest of the missing typings soon.

**Comment by KevinNovak** [comment]
Thanks for getting to this so quickly. However when I do a build, the typescript compiler gives back the following error:

> Exports and export assignments are not permitted in module augmentations.

![image](https://user-images.githubusercontent.com/11231402/91645957-479fef80-ea18-11ea-8c3e-50cfe0f9bd0a.png)

#12 should fix this issue.

However this requires typescript projects to use both imports from discord.js and discord.js-light:

![image](https://user-images.githubusercontent.com/11231402/91646164-496ab280-ea1a-11ea-83a4-dc14a433558c.png)

Which is not necessarily a bad thing, but something to be aware of, discord.js will still need to be installed in order to get the discord.js types that you haven't extended. I'm not sure if there's a way around that (like re-exporting all types somehow)

**Comment by timotejroiko** [comment]
added the rest of the typings and released in 3.2.7
closing this for now, let me know if anything goes wrong 👍

**Comment by KevinNovak** [comment]
Thank you, will do!!
