### ISSUE TITLE
TextChannel can never be an instance of User

### ISSUE THREAD

**Issue by NotSugden** [timotejroiko/discord.js-light#11]
https://github.com/timotejroiko/discord.js-light/blob/c0abe51ac8d70065cda3e2ff208ab74f3ee09008/classes.js#L283-L285

> `if (this instanceof Discord.User)`

but as you can see

> `class TextChannel extends T`

where T is `TextChannel` from discord.js

**Comment by timotejroiko** [comment]
Thanks. I was still thinking in terms of TextBasedChannel. But since TextBasedChannel is also implemented in NewsChannel i'll need to move it to init.js to avoid having to extend both.

**Comment by timotejroiko** [comment]
corrected in c292c7c

**Comment by timotejroiko** [comment]
closing this for now, let me know if there's anything else :) Thanks again!
