### ISSUE TITLE
Support discord.js-commando

### ISSUE THREAD

**Issue by zrenet** [timotejroiko/discord.js-light#14]
I want use discord.js-light with discord.js-commando.
Please let me know how to use both.

**Comment by timotejroiko** [comment]
I've never used commando, so i cant say how much of it is compatible with discord.js-light but if you want to give it a try, you will have to modify commando like this:

1. install discord.js-commando and discord.js-light
2. open the file `node_modules/discord.js-commando/src/client.js`
3. replace the 1st line from `const discord = require('discord.js');` to `const discord = require('discord.js-light');`

However its possible that some things will still break, in which case you will possibly need to make more edits to commando yourself.

**Comment by zrenet** [comment]
> I've never used commando, so i cant say how much of it is compatible with discord.js-light but if you want to give it a try, you will have to modify commando like this:
> 
> 1. install discord.js-commando and discord.js-light
> 2. open the file `node_modules/discord.js-commando/src/client.js`
> 3. replace the 1st line from `const discord = require('discord.js');` to `const discord = require('discord.js-light');`
> 
> However its possible that some things will still break, in which case you will possibly need to make more edits to commando yourself.

Yes, you right. I must fix a lot in Commando.
Thanks for support.
