### ISSUE TITLE
Commando Compatibility

### ISSUE THREAD

**Issue by WarenGonzaga** [timotejroiko/discord.js-light#16]
Just asking if this is compatible with commando by Discord.js?

**Comment by timotejroiko** [comment]
check #14

**Comment by WarenGonzaga** [comment]
Thanks @timotejroiko I got it... however if it is not yet supported the commando I will stick to discord.js for the meantime... how about the optional packages? Will it work with discord.js?

**Comment by timotejroiko** [comment]
yes, optional packages are the same in discord.js, you can see them here as well https://discord.js.org/#/docs/main/stable/general/welcome

**Comment by WarenGonzaga** [comment]
@timotejroiko oh now I realized it... thanks! I'm happy to close this issue for now! I hope a commando-light will appear from the wild... also... I'm willing to contribute here sometimes... 😅
