### ISSUE TITLE
Request to Add Bot

### ISSUE THREAD

**Issue by udit2303** [timotejroiko/discord.js-light#24]
Hey There 👋 Would you mind adding my bot to the README?
Links: 
**Multipurpose+**
[Website](https://music.udit.gq)
[top.gg](https://top.gg/bot/752391742770249800)  (Soon)
[discord.boats](https://discord.boats/bot/752391742770249800)

**CleverChat**
[top.gg](https://top.gg/bot/781834206325243954)
[discord.boats](https://discord.boats/bot/781834206325243954)

Thanks for taking your time in reading this and hopefully adding them.

**Comment by timotejroiko** [comment]
added!
