### ISSUE TITLE
Channel NSFW status

### ISSUE THREAD

**Issue by PrivateGER** [timotejroiko/discord.js-light#42]
The library seems to return an incorrect NSFW status for text channels in message objects when channel caching is disabled.
Despite the channel being NSFW, the property always is false.

**Comment by PrivateGER** [comment]
Fetching the channel manually using client.channels.fetch(message.channel.id) returns a channel with a properly set nsfw property.

**Comment by timotejroiko** [comment]
yes, Discord only sends channel IDs in the message payload, therefore message.channel is a partial if caching is disabled

**Comment by PrivateGER** [comment]
Thank you, noted. You maybe should mention that specifically in the readme, since it's an unexpected breaking change.

Also, in case you're interested in adding my bot to the README list: [Here it is.](https://discord.bots.gg/bots/438759579124236298)

**Comment by timotejroiko** [comment]
It is mentioned in the readme:

```md
Structures not marked as partial only guarantee the contents of its top-level properties. Linked structures such as message.channel or reaction.message may still be partials if not previously cached or fetched.
```

Feel free to make a PR to add your bot or i'll look into adding it later today

**Comment by timotejroiko** [comment]
Added your bot

**Comment by PrivateGER** [comment]
Yeah, that's sadly not going to happen, top.gg is **extremely** hostile towards NSFW bots for some reason. :/
Maybe I'll make my own badge image some day.
