### ISSUE TITLE
Typescript file out of date

### ISSUE THREAD

**Issue by scottbucher** [timotejroiko/discord.js-light#44]
![image](https://user-images.githubusercontent.com/47844014/111822408-23273a00-88ba-11eb-8a1f-b8189535c43f.png)

Docs says there is an option for caching members but it doesn't appear to be an option.

![image](https://user-images.githubusercontent.com/47844014/111822457-320dec80-88ba-11eb-9bae-1ba5594e9597.png)

**Comment by timotejroiko** [comment]
this option was added in response to the removal of fetchAllMembers, however im still unsure about it, need to review the code for it and might even remove it in the future, not sure yet. If you need it feel free to PR the typing for it.

**Comment by scottbucher** [comment]
I just realized it is up to date in master but it is not published to npm
