### ISSUE TITLE
<VoiceChannel>.join() don't work

### ISSUE THREAD

**Issue by MARCROCK22** [timotejroiko/discord.js-light#48]
Hello, i use \<VoiceChannel\>.join() and the bot say: 
```js
Error [VOICE_JOIN_CHANNEL]: You do not have permission to join this voice channel.
```
i view the code so \<VoiceChannel\>.joinable and \<VoiceChannel\>.viewable always is false.

**Comment by timotejroiko** [comment]
what are your your client options?

also what is the output of `voicechannel.permissionsFor(client.user)`?

**Comment by MARCROCK22** [comment]
```js
const client = new Discord.Client(
	{
		partials: ['PRESENCE', 'MESSAGE', 'REACTION'],
		http: { version: 7 },
		messageCacheMaxSize: 100,
		/*messageSweepInterval: 3600,
		messageCacheLifetime: 1800,*/
		messageEditHistoryMaxSize: 1,
		allowedMentions: { parse: [] },
		ws: {
			intents: 1701
		},
		cacheGuilds: true,
		cacheOverwrites: true,
		cacheRoles: true,
		cacheEmojis: false,
		cachePresences: false,
		cacheChannels: true,
		disabledEvents: [
			'messageUpdate',
			'messageDeleteBulk',
			'messageReactionRemove',
			'messageReactionRemoveAll',
			'messageReactionRemoveEmoji',
			'channelCreate',
			'channelUpdate',
			'channelDelete',
			'channelPinsUpdate',
			'roleCreate',
			'roleUpdate',
			'roleDelete',
			'inviteCreate',
			'inviteDelete',
			'emojiCreate',
			'emojiUpdate',
			'emojiDelete',
			'guildEmojisUpdate',
			'guildBanAdd',
			'guildBanRemove',
			'guildCreate',
			'guildUpdate',
			'guildDelete',
			'guildUnavailable',
			'guildMemberAdd',
			'guildMemberUpdate',
			'guildMemberRemove',
			'guildIntegrationsUpdate',
			'presenceUpdate',
			'typingStart',
			'userUpdate',
			'voiceStateUpdate',
			'webhookUpdate',
			'rest'
		]
	}
);
```
and
```js
voicechannel.permissionsFor(client.user) //null
```

**Comment by timotejroiko** [comment]
Are you deleting members?

What is the output of channel.guild.me?

**Comment by MARCROCK22** [comment]
nop, and
```js
GuildMember {
  guild: [Guild],
  joinedTimestamp: 1592936823788,
  lastMessageID: '828999470539604008',
  lastMessageChannelID: '692021459702251550',
  premiumSinceTimestamp: null,
  deleted: false,
  nickname: null,
  _roles: [Array],
  _userID: 'the bot id'
}
```

**Comment by timotejroiko** [comment]
try uninstalling both discord.js and discord.js-light and install only discord.js-light

**Comment by MARCROCK22** [comment]
same error

**Comment by timotejroiko** [comment]
it works fine for me...

try logging `channel.guild.members.resolve(client.user)`

**Comment by MARCROCK22** [comment]
![image](https://user-images.githubusercontent.com/57925328/113732826-eafc6580-96c7-11eb-94f6-ea2d0b8a38e9.png)

**Comment by MARCROCK22** [comment]
![image](https://user-images.githubusercontent.com/57925328/113732885-f780be00-96c7-11eb-82c9-cca60b30a7bf.png)

**Comment by timotejroiko** [comment]
log client.user

**Comment by MARCROCK22** [comment]
![image](https://user-images.githubusercontent.com/57925328/113733459-7c6bd780-96c8-11eb-8a2b-59ec8918a242.png)

**Comment by timotejroiko** [comment]
log client.users.resolveID(client.user)

**Comment by MARCROCK22** [comment]
null

**Comment by timotejroiko** [comment]
log client.users.cache

**Comment by MARCROCK22** [comment]
![image](https://user-images.githubusercontent.com/57925328/113737708-47618400-96cc-11eb-984b-e0d2dd0cb1c8.png)

**Comment by timotejroiko** [comment]
log client.user instanceof client.users.holds
also log client.users.holds

**Comment by MARCROCK22** [comment]
![Uploading image.png…]()

**Comment by MARCROCK22** [comment]
![image](https://user-images.githubusercontent.com/57925328/113737973-8263b780-96cc-11eb-86af-91846c4c72fc.png)

**Comment by timotejroiko** [comment]
the second one should be User extends Base...

are you doing any kind of class extensions or overriding anything? if not, the only way this would be happening is if you have wrong/conflicting versions of discord.js, so again, uninstall all discord.js and discord.js-light, delete node_modules, and install ONLY discord.js-light. do not install discord.js

**Comment by MARCROCK22** [comment]
i extend the user class

**Comment by timotejroiko** [comment]
does it work if you delete the user extension?

**Comment by MARCROCK22** [comment]
i have another proyect in ts, and work, i dont extend any class, just i do:
```
class Cliente extends Client {
//...
}
```
and work

**Comment by timotejroiko** [comment]
try again with v3.5.9

**Comment by MARCROCK22** [comment]
Work
