### ISSUE TITLE
RangeError: "StageChannel" is not a valid extensible structure.

### ISSUE THREAD

**Issue by cxllm** [timotejroiko/discord.js-light#54]
Hi, I'm using the discord.js-light master build, and whenever I start it up using the master build, I get this error:
![image](https://user-images.githubusercontent.com/59397232/116510074-3d423800-a8bc-11eb-879f-3461df931518.png)
and I'm not sure if the error is my fault or if it's to do with the library. Is there anything I can do to fix it, or is there any fix on the way?
Thanks!

**Comment by timotejroiko** [comment]
uninstall both discord.js and discord.js-light
then install master again: `npm install timotejroiko/discord.js-light`
do not install discord.js

**Comment by cxllm** [comment]
Ok, I shall try that, thank you!

**Comment by cxllm** [comment]
This has fixed the problem, thanks so much
