### ISSUE TITLE
DMChannel does not have "recipient" in v3.5.11

### ISSUE THREAD

**Issue by cjh980402** [timotejroiko/discord.js-light#64]
DMChannel of 4.0.0-dev has "recipient" but DMChannel of 3.5.11 does not have "recipient".
![image](https://user-images.githubusercontent.com/23624124/123592847-bf9d9880-d828-11eb-891e-a0e0a639888f.png)

**Comment by timotejroiko** [comment]
how did you fetch/create the DMchannel? if has recipient when you use client.channels.fetch() and user.createDM()

**Comment by cjh980402** [comment]
I just the send message in DMChannel.
However, I fetched only my account user(caching true) and send DMNotice when bot start. Then, discord.js v13 cached that DMChannel (discord.js v12 does not). I think it make difference of 4.0.0-dev and 3.5.11.
Thank you for your reply.

**Comment by timotejroiko** [comment]
ah ok, caching behavior in v13/v4 is still not complete so there can be some differences.
