### ISSUE TITLE
Privileged Intents Support

### ISSUE THREAD

**Issue by Neoration** [timotejroiko/discord.js-light#66]
Private Intents does not work on commit "7c753b9d6a59ed149464d14415123772fa9e49ab".
I wrote the code like this.
```ts
const client = new Client({
  intents: [Intents.FLAGS.GUILD_MESSAGES, Intents.PRIVILEGED],
});

client.on("message", (msg) => {
  if (msg.author.bot) return;
  console.log(msg.author.presence.status);
});
```
However, only offline appears in the console log.

Also, it doesn't seem to work in the official release of v3.5.11.
This code was created when using the above version, and will only output offline to the console log.
```ts
const client = new Client({
  ws: {
    intents: [Intents.FLAGS.GUILD_MESSAGES, Intents.PRIVILEGED],
  },
});

client.on("message", (msg) => {
  if (msg.author.bot) return;
  console.log(msg.author.presence.status);
});
```

**Comment by timotejroiko** [comment]
They should work, if you console.log(client.options.intents) you should see the correct value.

The problem is that presences are not cached by default, you need to set `cachePresences:true` in your client options to use them in discord.js-light

**Comment by Neoration** [comment]
Thank you. It's been resolved.
