### ISSUE TITLE
TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by zeteticl** [timotejroiko/discord.js-light#71]
Hey, I use the below code and got error, how can i fix it?

`TypeError: Cannot read property 'slice' of null

 let high = parseInt(num.slice(0, -10)) || 0;
                                        ^

function channelFilter(channel) {
	return !channel.messages || Discord.SnowflakeUtil.deconstruct(channel.lastMessageId).timestamp < Date.now() - 3600000;
}

	ChannelManager: {
			maxSize: Infinity, // 
			sweepFilter: () => channelFilter, // remove manually cached channels according to the filter
			sweepInterval: 3600
		},
		GuildChannelManager: {
			maxSize: Infinity, // 
			sweepFilter: () => channelFilter, // remove manually cached channels according to the filter
			sweepInterval: 3600
		},

**Comment by timotejroiko** [comment]
change the filter function to this:

```js
function channelFilter(channel) {
return !channel.lastMessageId || Discord.SnowflakeUtil.deconstruct(channel.lastMessageId).timestamp < Date.now() - 3600000;
}
```

I will update it in the readme as well.
