### ISSUE TITLE
LimitedCollection Typescript Error

### ISSUE THREAD

**Issue by VascoBotelho** [timotejroiko/discord.js-light#74]
Hello, I'm having a typescript error.
It's warning me that 'All declarations of "LimitedCollection' must have identical type parameters" in `node_modules/discord.js-light/client.d.ts:35:12` and `node_modules/discord.js-light/node_modules/discord.js/typings/index.d.ts:1084:14`

node: `v16.6.0`
discord.js: `v13.1.0`
discord.js-light: `v4.1.4`
![image_2021-09-12_183650](https://user-images.githubusercontent.com/48020247/132997217-dbe0852b-4237-4cce-9a58-6eea91e8b635.png)

**Comment by timotejroiko** [comment]
hello,

i added a fix to the v4 branch, can you test it? `npm install timotejroiko/discord.js-light#v4`

**Comment by VascoBotelho** [comment]
I have tested, and it's not showing the error any more.
Thank you

**Comment by timotejroiko** [comment]
cool, i'll update it on npm soon
