### ISSUE TITLE
`guildCreate` doesn't get triggered on init

### ISSUE THREAD

**Issue by tyuop077** [timotejroiko/discord.js-light#78]
Currently there's no way to get guilds on launch with `ChannelManager` and `GuildManager` being LimitedCollection with size = 0 without fetching them with `client.guilds.forge(exampleGuildId).channels.fetch()` (ChannelManager) and `client.guilds.forge(exampleGuildId).fetch()` (GuildManager) as example.

`client.on("raw",console.log)` shows, that we receive `GUILD_CREATE` events (with channels and threads) without getting them on `guildCreate` or `guildUpdate` (`shardConnect` works for this option, but will do it only on sharding).

I was collecting `parentId`'s of guild channels and thread parentIds, so there's no way to get them at launch without fetching.

**Code:**
```ts
...

const categories = new Collection<Snowflake, Snowflake>() // { channel => category }
const threads = new Collection<Snowflake, Snowflake>() // { thread => channel }

// categories and threads are always synced:
client.on("channelCreate",this._onChannelCreate);
client.on("channelUpdate",this._onChannelUpdate);
client.on("channelDelete",this._onChannelDelete);
client.on("threadCreate",this._onThreadCreate);
client.on("threadDelete",this._onThreadDelete);
client.on("threadUpdate",this._onThreadUpdate);
client.on("threadListSync",this._onThreadSync);

const channels = await this.client.guilds.forge(config().constants.trustedGuild).channels.fetch(); // can't receive on guildUpdate or guildCreate
// same with threads

channels.forEach(channel => {
   if (!channel.parentId || !channel.isText()) return;
   this.categories.set(channel.id, channel.parentId)
})

...
```

**messageCreate:** `(leveling.channelMultipliers contains { Snowflake: number } with channel/category ids and multiplier values)`
```ts
const channelId = message.channel.isThread() ? this.threads.get(message.channelId) : message.channelId;
const categoryId = channelId ? this.categories.get(channelId) : null;

const channelMultiplier = leveling.channelMultipliers[channelId!] ?? leveling.channelMultipliers[categoryId!] ?? 0;

console.log(`${channelId}'s multiplier is ${channelMultiplier}`);
```

**Comment by timotejroiko** [comment]
guildCreate and guildUpdate should work correctly after the client is ready. The initial GUILD_CREATE events that are sent to fill up the cache at login are not emitted by the discord.js guildCreate event, they are handled internally to decide when the client should become ready.

If you're looking for the initial GUILD_CREATE events, you have to use shardConnect or raw.

Is this what you're asking? im not sure im understanding the issue very well.

**Comment by tyuop077** [comment]
@timotejroiko Yeah, I thought of maybe implementing a new before-ready guild create event, because with shardConnect I still won't get thread objects, only guilds. So `raw` is only way to go with there :(

**Comment by tyuop077** [comment]
thank you!
