### ISSUE TITLE
Can't set maxSize on cache.

### ISSUE THREAD

**Issue by LosTigeros** [timotejroiko/discord.js-light#79]
Hey, according to your example about caching roles only for the bot itself and ignoring all other roles you set the `maxSize` to `0`.
In your types however there's only `forceSet` function defined and `maxSize` is not.
Because of that, TypeScript throws me an error.
![image](https://user-images.githubusercontent.com/6253928/135460027-31edd7a8-7929-4d77-a520-0d29142cbab0.png)

**Comment by timotejroiko** [comment]
cast it as Discord.LimitedCollection

**Comment by LosTigeros** [comment]
Oh okay that works. Thanks.
What about this one?
![image](https://user-images.githubusercontent.com/6253928/135461584-8a1b720a-ab69-43cb-82a9-e98ef5c42603.png)

**Comment by timotejroiko** [comment]
i'll need to add that one to the typings, will do it soon. for now you can try `(role as any).partial`

**Comment by timotejroiko** [comment]
hey i added the typings, can you test it? `npm i timotejroiko/discord.js-light#v4`

**Comment by LosTigeros** [comment]
Hey, yes it shows them fine now.

**Comment by timotejroiko** [comment]
released

**Comment by LosTigeros** [comment]
Okay, thanks again.
If you want, you can add [Shoob](https://shoob.gg/) bot to the list.

**Comment by timotejroiko** [comment]
> If you want, you can add [Shoob](https://shoob.gg/) bot to the list.

Feel free to make a PR for it
