### ISSUE TITLE
how do i get all channels in a guild?

### ISSUE THREAD

**Issue by Milo123459** [timotejroiko/discord.js-light#8]
so If I pass in the options for no channelCaching, how can I get all channels in a guild? Would It be like:
```js
<Guild>.channels.fetch();
//do something
<Guild>.channels.cache.deleteAll();
```
or does it automatically remove it from the cache?

**Comment by timotejroiko** [comment]
(answered on discord, but reposting here for visibility)

You can use `<Guild>.channels.fetch(false)` which will fetch all channels and return a collection of channels, without caching them.
