### ISSUE TITLE
How to send webhook in the thread?

### ISSUE THREAD

**Issue by zeteticl** [timotejroiko/discord.js-light#86]
`const channel = await client.channels.fetch(discord.channelId);`
	`	let webhooks = await channel.fetchWebhooks();`
`	webhook = webhooks.find(v => {`
			`	return v.name == 'XOXO' && v.type == "Incoming";`
	`		})`
`	await webhook.send({
			content: text,
			username: message.myName.username,
			avatarURL: message.myName.avatarURL
		});`

It is work in channel, but get error in thread

`
error TypeError: channel.fetchWebhooks is not a function
`

**Comment by timotejroiko** [comment]
According to the [discord.js documentation](https://discord.js.org/#/docs/main/stable/class/ThreadChannel), there is no `fetchWebhooks` method on ThreadChannels.

Im not sure if there is a reason for it not existing, you can try asking the discord.js developers.

In the meanwhile you can try using `guild.fetchWebhooks()` and see if it has any webhooks you're looking for in there.

**Comment by zeteticl** [comment]
Thankyou so much.
Finally i done my work
