### ISSUE TITLE
How can I install discord.js-light master using npm?

### ISSUE THREAD

**Issue by bibi0019** [timotejroiko/discord.js-light#96]
I tried to install the master branch using npm but it give me that error
![image](https://user-images.githubusercontent.com/49600231/196663434-dad6bcfe-4dfc-4a3d-8b1e-b2be6f829a57.png)

**Comment by timotejroiko** [comment]
master is very outdated, dont use it

**Comment by bibi0019** [comment]
but I am using discord.js v14

**Comment by timotejroiko** [comment]
djs-light currently does not support djs v14, please see #95.

If you have a use case that cannot be done with normal discord.js please add a comment there and i will look into it when i have time.

master has not been updated in over 1 year, its impossible to keep up with discord.js updates as they have a whole team and i am only one person.
